# Site
name: "Francisco Ugalde"
title: "franciscougalde.com"
description: "Blog sobre tecnología, desarrollo web y móvil"
logo: 'assets/images/logo-favicon.png'
favicon: 'assets/images/logo-favicon.png'
#baseurl: /mediumish-theme-jekyll
baseurl: ''
google_analytics: 'UA-106120347-1'
disqus: 'fjugaldev'
mailchimp-list: 'https://franciscougalde.us17.list-manage.com/subscribe/post?u=6f7556cfd349e68353c4ae1ef&id=4235ff6e34'
include: ["_pages"]
permalink: /:year/:month/:day/:title/

# Authors
authors:
  fjugaldev:
    name: Francisco Ugalde
    display_name: Frλn
    gravatar: f9e54876253f3dc4a999dc61e1f00a8e
    email: fjugal.dev@franciscougalde.com
    web: https://www.franciscoygalde.com
    twitter: https://twitter.com/fjugaldev
    description: "ѕeɴιor ѕoғтwαre eɴɢιɴeer | Symfony Lover | Apasionado a las nuevas tecnologías y la arquitectura de software."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/categoria/:name/'

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    css_class: 'syntax'

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-2046792861254371"
adsense-data-ad-slot: "5927756201"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, output-pub]
